add p2p-webrtc-direct pattern
whyrusleeping/mafmt pull request #14
Opened 2018-12-20 11:57 UTC by backkem

This PR ports the `p2p-webrtc-direct` pattern from `js-mafmt` in preparation of a `go-libp2p-webrtc-direct` transport. It depends on:
- multiformats/go-multiaddr-dns#11
- multiformats/go-multiaddr#93

I'll probably need some help with the dependency management.

2019-02-27 12:20 UTC, raulk requested changes
Minor comments. Overall LGTM, although I'm worried about turning mafmt into a *-import module in the long run.

To avoid stalling, I'll commit the changes myself on your branch.

EDIT: I can't because this repo is under whyrusleeping's account rather than in the multiformats org. I'll clone it there, migrate downstream usages in our control, and port over this PR.

2019-02-27 12:20 UTC, raulk commented on patterns.go
> +var _DNS = Or(
If this is copied from js-mafmt, the _ convention usually denotes unexported vars. In go you can lowercase this.

2019-02-27 12:20 UTC, raulk commented on patterns.go
> +	And(_DNS, Base(ma.P_TCP)),
This one is wonky at origin: https://github.com/multiformats/js-mafmt/issues/40

2019-03-01 10:51 UTC, backkem commented
This was added in multiformats/go-multiaddr-fmt.

2019-03-01 10:51 UTC, closed without merging